// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subheadline?: string;
  excerpt: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content: PortableTextBlock[];
  reading_time?: string;
  is_lead_hero?: boolean;
  is_secondary_hero?: boolean;
  is_featured?: boolean;
  is_popular?: boolean;
  popular_rank?: number;
  popular_reads?: string;
  published_at?: Date | string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    articles: Article;
    posts: Article;
  }
}